const ADD_SUCCESS = 'notes/ADD_SUCCESS';
const CHANGE_FILTER = 'notes/CHANGE_FILTER';
const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCESS1 = 'notes/FETCH_SUCCESS1';
const FETCH_SUCCESS_BY_CATEGORY = 'notes/FETCH_SUCCESS_BY_CATEGORY';
const FETCH_SUCCESS_BY_ID = 'notes/FETCH_SUCCESS_BY_ID';
const FETCH_CATEGORIES = 'notes/FETCH_CATEGORIES';
const FETCH_ERROR = 'notes/FETCH_ERROR';
const ADD_TO_CART = 'notes/ADD_TO_CART';
const REMOVE_FROM_CART = 'notes/REMOVE_FROM_CART';
const INCREMENT_AMOUNT = 'notes/INCREMENT_AMOUNT';
const DECREMENT_AMOUNT = 'notes/DECREMENT_AMOUNT';

export default {
  ADD_SUCCESS,
  FETCH_SUCCESS_BY_CATEGORY,
  FETCH_SUCCESS_BY_ID,
  FETCH_CATEGORIES,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS1,
  FETCH_ERROR,
  REMOVE_FROM_CART,
  ADD_TO_CART,
  INCREMENT_AMOUNT,
  DECREMENT_AMOUNT,
};
